import "./css/style.css";
import { Lexend } from "next/font/google";

const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lexend.className}> {/* Apply the font class to <html> */}
      <body className="bg-gray-50 tracking-tight text-gray-900 antialiased">
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>
      </body>
    </html>
  );
}
